#!/bin/bash

cd $INSTALLPATH/data/seed
jar -xvf Adempiere_pg.jar

sed -i "/CREATE SCHEMA adempiere;/d" Adempiere_pg.dmp
sed -i "/ALTER SCHEMA adempiere OWNER TO adempiere;/d" Adempiere_pg.dmp
sed -i "s/SET search_path = adempiere, pg_catalog;/SET search_path = $IDEMPIERE_DB_SCHEMA, pg_catalog;/" Adempiere_pg.dmp
sed -i "s/adempiere\./$IDEMPIERE_DB_SCHEMA\./" Adempiere_pg.dmp
sed -i "s/OWNER TO adempiere/OWNER TO $IDEMPIERE_DB_USER/" Adempiere_pg.dmp

echo -------------------------------------
echo Create User and Database
echo -------------------------------------

SQL_CREATE_ROLE_SU="CREATE ROLE $IDEMPIERE_DB_USER LOGIN PASSWORD '$DBPASS'"
SQL_ALTER_ROLE_SU="ALTER ROLE $IDEMPIERE_DB_USER WITH SUPERUSER"
SQL_ALTER_ROLE_SU_RDS="GRANT RDS_SUPERUSER to $IDEMPIERE_DB_USER"
SQL_GRANT_MASTER="GRANT $IDEMPIERE_DB_USER TO $IDEMPIERE_DB_USER_SU"
SQL_CREATE_DB="CREATE DATABASE $IDEMPIERE_DB_NAME WITH ENCODING='UNICODE' OWNER $IDEMPIERE_DB_USER"
SQL_CREATE_SCHEMA="CREATE SCHEMA IF NOT EXISTS $IDEMPIERE_DB_SCHEMA AUTHORIZATION $IDEMPIERE_DB_USER"
SQL_CREATE_EXTENSION_UUID="CREATE EXTENSION \"uuid-ossp\""
SQL_SET_SEARCH_PATH="ALTER ROLE $IDEMPIERE_DB_USER SET search_path TO $IDEMPIERE_DB_SCHEMA"

echo ""
psql -h $PGHOST -p $PGPORT -U $IDEMPIERE_DB_USER_SU -c "$SQL_CREATE_ROLE_SU"
psql -h $PGHOST -p $PGPORT -U $IDEMPIERE_DB_USER_SU -c "$SQL_ALTER_ROLE_SU"
psql -h $PGHOST -p $PGPORT -U $IDEMPIERE_DB_USER_SU -c "$SQL_ALTER_ROLE_SU_RDS"
psql -h $PGHOST -p $PGPORT -U $IDEMPIERE_DB_USER_SU -c "$SQL_GRANT_MASTER"
psql -h $PGHOST -p $PGPORT -U $IDEMPIERE_DB_USER_SU -c "$SQL_CREATE_DB"
psql -h $PGHOST -p $PGPORT -U $IDEMPIERE_DB_USER -d $IDEMPIERE_DB_NAME -c "$SQL_CREATE_SCHEMA"
psql -h $PGHOST -p $PGPORT -U $IDEMPIERE_DB_USER -d $IDEMPIERE_DB_NAME -c "$SQL_CREATE_EXTENSION_UUID"
psql -h $PGHOST -p $PGPORT -U $IDEMPIERE_DB_USER -d $IDEMPIERE_DB_NAME -c "$SQL_SET_SEARCH_PATH"
psql -h $PGHOST -p $PGPORT -U $IDEMPIERE_DB_USER -d $IDEMPIERE_DB_NAME -f Adempiere_pg.dmp

